### ISSUE TITLE
Add Leadership page

### ISSUE THREAD

**Issue by ronaldtse** [riboseinc/www.isotc154.org#24]
Add leadership page to list out current chair, committee manager and conveners. This was from CAG meeting Dec 10, 2019.

**Comment by strogonoff** [comment]
In [each member’s dataset](https://github.com/iso-tc154/www.isotc154.org/tree/master/_members) there’s a field `role`, containing a machine-readable identifier of that role. I will assume the following role IDs correspond to leadership roles:

- `committee-manager[-*]`
- `convener[-*]`
- `chair`

**Comment by strogonoff** [comment]
@ronaldtse in the latest update, Members page adds Leadership section, which shows only members whose roles match above conditions.

The “current members” section, now renamed “all current members” for clarity, shows everyone active, which unfortunately includes leadership as well. This is the quick solution without changing the data structure for members and working within the constraints of Liquid’s very limited array filtering facilities.

I will make the following improvements while this issue is open:

* Make whole member cards clickable (interferes with text selection) or make it clearer which parts of those are clickable links.

It is possible that one of the following changes will be required:

* Turn the Leadership section into a separate page, to follow the original issue description exactly
* Make sure current members doesn’t show leadership (i.e., one member is only shown on Members page once). This would be best addressed with role definition data later, adding role types (e.g. “convener”) and marking certain role types as leadership.

I believe neither of those two is critical, but do let me know.

**Comment by strogonoff** [comment]
Adding screenshot of the updated Members page, while CI is pending:

<img width="1499" alt="Screenshot 2019-12-18 at 4 25 51 AM" src="https://user-images.githubusercontent.com/292959/71031540-8887fa80-214e-11ea-9dc8-21012db3ab55.png">

**Comment by strogonoff** [comment]
Update in https://github.com/iso-tc154/www.isotc154.org/commit/fb3aab7b593d2c33de1b13a648bd38e4d11f7fc9

**Comment by strogonoff** [comment]
@ronaldtse 

From our chat it transpired that we can’t infer leadership board from roles, so I added a setting to specify exact member IDs to be shown leadership.

Please feel free to edit [this part of _config.yml](https://github.com/iso-tc154/www.isotc154.org/blob/master/_config.yml#L12) or let me know member IDs that should be shown under leadership.

**Comment by ronaldtse** [comment]
@strogonoff the `_config.yml` file is now updated.

**Comment by ronaldtse** [comment]
All done, closing.
