### ISSUE TITLE
Add roles for "Co-Chair 7372/UNTDED Joint Maintenance Agency"

### ISSUE THREAD

**Issue by ronaldtse** [riboseinc/www.isotc154.org#27]
There are two "Co-Chairs" of the "ISO 7372/UNTDED Joint Maintenance Agency":

* Sue Probert
* Hongru (Judy) Zhu

We want to tag them as such.

**Comment by strogonoff** [comment]
@ronaldtse “Convenor” isn’t suitable, unlike other groups? (https://www.isotc154.org/groups/ma/)

**Comment by ronaldtse** [comment]
For the the JMA it should be “co-chair” because it is not a working group, it’s a separate entity that is created between UNECE and ISO at the top level.

**Comment by strogonoff** [comment]
> at the top level

Do you mean it’s part of the TC from one angle and a _sibling_ of the TC from another angle?

**Comment by strogonoff** [comment]
@ronaldtse Representing MA as a WG will bite us in many other ways later on.

For now I filed https://github.com/iso-tc154/www.isotc154.org/issues/28 so feel free to follow up there, later at some point we’ll have to split it into a separate entity instead of piling on special cases for handling a group-that-is-not-a-group.
